
networks:
  monitoring-network:
    driver: bridge
    name: monitoring-network

services:
  ingestion-api:
    build: ./ingestion-api
    hostname: ingestion-api
    container_name: ingestion-api
    ports:
      - "3001:3001"
    env_file:
    - path: ./ingestion-api/.env
    networks:
      - monitoring-network

  db-worker:
    build: ./db-worker
    hostname: db-worker
    container_name: db-worker
    env_file:
    - path: ./db-worker/.env
    
    network_mode: host   

  query-api:
    build: ./query-api
    hostname: query-api
    container_name: query-api
    env_file:
    - path: ./query-api/.env
      required: true # default
    ports:
      - "3002:3002"
    networks:
      - monitoring-network